### ISSUE TITLE
Add po for translations.

### ISSUE THREAD

**Issue by albanobattistella** [david-swift/Memorize#11]
Hi,

this app is really nice!
Could you please provide the po for translations?
Thank you.
Regards.
A

**Comment by david-swift** [comment]
Thanks for opening the issue! Memorize is localized using the [Localized.yml](https://github.com/david-swift/Memorize/blob/main/Sources/Model/Localized.yml) file. Find more information about this approach [here](https://github.com/AparokshaUI/Localized). I'm aware that many people translating apps prefer working with a UI instead of a text editor, so I'm currently developing an app for localizing apps built using that approach. Currently, translations can be added directly into the YML file only.

**Comment by david-swift** [comment]
I will add instructions to the README once the UI is available.

**Comment by Vistaus** [comment]
That would be great! I will provide the Dutch translation once the UI is available. 🙂

**Comment by david-swift** [comment]
A short description of the new translation method is available [here](https://github.com/david-swift/Memorize?tab=readme-ov-file#localization).
