### ISSUE TITLE
More colorful brand colors

### ISSUE THREAD

**Issue by bertob** [david-swift/Memorize#19]
### Is your feature request related to a problem? Please describe.

The current brand colors are monochrome.

### Describe the solution you'd like

It's recommended to use brand colors that are actually colorful. We know the guidelines are not complete yet in this regard, but we're learning as we go and this will be updated :)

Example for colors that would work here:

- light: #9fe38c
- dark: #49823d

![image](https://github.com/david-swift/Memorize/assets/1908896/b2197331-0206-44c6-997d-feb5111428f2)

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by david-swift** [comment]
Thanks for opening the issue, @bertob!

This has actually changed with the lasted release, 0.1.4.

![Screenshot from 2024-03-10 21-45-36](https://github.com/david-swift/Memorize/assets/106754840/d0654bd0-ecf7-44bf-aa9a-915f0d8ff534)

I chose yellow because I associate it with sticky notes and highlighters which remind me of studying, but I think both (green & yellow) work for a flashcards app.

What do you as a designer think about them?

**Comment by bertob** [comment]
Ah nice, yeah the yellow works too :)
