### ISSUE TITLE
Replacing the view switcher in sets with "Study" and "Test" buttons

### ISSUE THREAD

**Issue by bragefuglseth** [david-swift/Memorize#24]
The current set layout uses a view switcher with 3 options: "Overview", "Study" and "Test". When "Study" or "Test" is chosen, the sidebar hides. This setup leads to some problems:

- The sidebar hiding behavior is confusing. If you're not aware of how it works, it may come as a surprise, and you might end up struggling to get it back again.
- It's possible to navigate directly from tests and study sessions to other parts of the app, without interrupting the current test/study session. This allows for "cheating" by peeking at the flash cards and going straight back to the test, and removes the feeling of being in a focused "session" of anything at all.
- The way tests and study sessions are cancelled is ambiguous.

To solve this, we could e.g. make the study and test modes available through buttons that open dedicated views with back buttons:

![Skjermbilde fra 2024-03-18 22-20-35](https://github.com/david-swift/Memorize/assets/91388039/900b141c-5a89-4001-a166-bb0796d72f65)

This is a cleaner navigation model that would solve the problems above and make the relationship between the different app states clearer. It would also easen the process of making the app adaptive.

**Comment by david-swift** [comment]
I started implementing the new design on the branch [46](https://github.com/david-swift/Memorize/tree/46). While I love the look, I don't think the study progress should be lost when leaving the study view, as studying might be a long process (it is okay for testing I think). What would you think about keeping the current logic, but with the new navigation? I could polish the "continue studying" view in order to present details about the current study session so that it is less confusing. What do you think about it?

**Comment by bragefuglseth** [comment]
Sounds good to me. Just reworking the navigation would be great.
